# Generated by Django 2.1.3 on 2019-01-07 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(db_index=True, max_length=50)),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('adress', models.CharField(db_index=True, max_length=150)),
                ('time', models.CharField(db_index=True, max_length=100)),
                ('price', models.CharField(db_index=True, max_length=50)),
                ('info', models.TextField()),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
    ]
