# Generated by Django 2.1.3 on 2019-01-12 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_auto_20190107_2101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='adress',
            new_name='address',
        ),
    ]
